### ISSUE TITLE
One of `DjangoBehaviorTest`s seems to fail with `django>=3.0`

### ISSUE THREAD

**Issue by ThirVondukr** [ThirVondukr/passlib#2]

**Comment by dlondonmedina** [comment]
I researched this and it has to do with Django making sha256 the preferred algorithm rather than sha1 on version 3.1. The behavior in the `check_password` method that's called in that test on line 758:
```
# check against valid password
        assert user.check_password(secret)
```
causes the password to be rehashed with sha256, so the subsequent password check on line 770 fails.

I can handle this, but something worth considering is which version of Django we should support. Thoughts?

**Comment by ThirVondukr** [comment]
Contexts for different django versions seems to be here: https://github.com/ThirVondukr/passlib/blob/f7744ed803e4c6b3f61be24bc68a7afdd5f17e09/passlib/apps.py#L97

Currently supported django versions are 4.2 and 5: https://endoflife.date/django we could just define context for django 3.1 that will use sha256?

**Comment by dlondonmedina** [comment]
Yeah that's what I was thinking! I have a PR that's almost ready.
